### ISSUE TITLE
CBOR encoding specification for IDL types

### ISSUE THREAD

**Issue by armaniferrante** [oasislabs/oasis-rs#119]
All runtime clients need to implement this specification to send properly serialized requests to the runtime.

**Comment by gedw99** [comment]
This is something that interests me. My use case is writing golang compiled to wasm to work with wasi.

So maybe I can use the IDL to codegen the RPC from. Or perhaps something similar.

**Comment by nhynes** [comment]
> maybe I can use the IDL to codegen the RPC from

Yes, absolutely. You can apply similar ideas from the `visitor` and `rpc` modules in `mantle-build` in golang. We'll eventually want a golang version of mantle. If you're interested, we could work together on building the RPC IR (the format in `mantle-rpc`) which you could retarget to whatever IDL you want (like (proto|flat)buffers). If you let me know what compiler you're using, I can take a look into how the implementation would work.
