### ISSUE TITLE
Address type should have some easy way to make a zero address

### ISSUE THREAD

**Issue by omitar** [oasislabs/oasis-rs#196]
After some time we figured out that `Address([0u8; 20])` works. But maybe `Address.zero()` could be nicer.

**Comment by omitar** [comment]
So not just easy way (there is `Address::default()`) but also a more literal name. `Address::zero` could be made an alias for `Address::default`.

**Comment by nhynes** [comment]
Why is this needed?

**Comment by omitar** [comment]
When implementing ERC-20 it looks like it is commonly used: it is checked if destination or source addresses are not zero, and also it is used as source address when minting and as burn address when burning.

**Comment by omitar** [comment]
I would just think it makes code more self-explanatory without adding any burden really.

**Comment by nhynes** [comment]
So calling the zero address in Oasis is equivalent to CREATE. The erc20 semantics don’t carry over, which is why a direct port isn’t quite advisable.

**Comment by omitar** [comment]
> So calling the zero address in Oasis is equivalent to CREATE.

I am not sure if I understand this. What you mean by "calling the zero address"? I just want to check if somebody passes zero address to the RPC call.

**Comment by mitar** [comment]
There is now `Address::zero()`. Thanks!
