### ISSUE TITLE
`oasis build` produces quickstart.wasm

### ISSUE THREAD

**Issue by rebekahkim** [oasislabs/oasis-rs#222]
**Description of the bug**
`oasis build` in the `service` directory produces `quickstart.wasm`. When building in `app`, this causes `TypeError: Cannot read property 'deploy' of undefined` 

**Steps to reproduce**
1. `oasis init <Service>`
2. Write the <Service>
3. `oasis build` in `service`
4. `quickstart.wasm` produced in `service/target/wasm32-wasi/release`

**Expected behavior**
`oasis build` produces `<service>.wasm`

**Environment**
 - OS: macOS Mojave

**Comment by nhynes** [comment]
I wasn't able to reproduce this error. I ran `rg -i quickstart` on the repo and couldn't find anything that might have produced that file.

**Comment by rebekahkim** [comment]
Hmm yeah I couldn't reproduce this after updating the CLI. Maybe it's the old version of the CLI I installed few weeks ago that was the problem?

Feel free to close.
