### ISSUE TITLE
error: `profile.local` is missing field: `gateway`

### ISSUE THREAD

**Issue by rebekahkim** [oasislabs/oasis-rs#223]
**Description of the bug**
It seems like the config file (`~/.config/oasis/config.toml`) is not configured properly.

**Steps to reproduce**
1. `oasis test` in `app`
2. See error
`error: `profile.local` is missing field: `gateway`.`

**Expected behavior**
`oasis test` runs

**Environment**
 - OS:  macOS Mojave

**Additional information**
`$ oasis config profile` shows the following: 

```
[default]
endpoint = "wss://web3.devnet.oasiscloud.io/ws"
private_key = "0x[redacted]"

[local]
mnemonic = [redacted]
endpoint = "ws://localhost:8546"
```

**Comment by nhynes** [comment]
`oasis set-toolchain latest`  should do the trick. You'll also want to regenerate your config (or salvage the current one by running `sed 's/endpoint/gateway/g` and `s/(mnemonic|private_key)/credential`).

**Comment by nhynes** [comment]
(tentatively closing. please feel free to reopen)
