### ISSUE TITLE
Addresses stored in topics should not be hashed

### ISSUE THREAD

**Issue by mitar** [oasislabs/oasis-rs#244]
**Description of the bug**

When storing addresses in events and making them indexed they should not be hashed, but zero padded in topics.

**Additional information**

It is like that in Ethereum.

**Comment by nhynes** [comment]
I'm going to label this one wontfix because all of our clients just hash the address, and none of our services are compatible with ethereum clients anyway.

**Comment by mitar** [comment]
But this is major incompatibility, and also this is an important feature, to be able to have an address in the event stored, without having to store it twice.

**Comment by nhynes** [comment]
if you wanted to use the address as a topic in the bloom filter, you already know the address

**Comment by mitar** [comment]
Yes, but if I find an event through another topic, and then want to use the other address, I cannot. Or I have to store it again as a payload. Also, we do not know in advance which topics people will want in the future to use as data. So one would have to store addresses both as topic and as payload to make it useful for consumers who might want to have an address.

**Comment by mitar** [comment]
Awesome! Thanks.
