### ISSUE TITLE
Client generator that uses serde-eth

### ISSUE THREAD

**Issue by armaniferrante** [oasislabs/oasis-rs#57]
Client that serializes rpc args using serde_eth::to_vec instead of serde_cbor.

**Comment by armaniferrante** [comment]
Punted out of release 3.

**Comment by nhynes** [comment]
Let's see if we can just keep deferring this forever.

**Comment by armaniferrante** [comment]
Context on closing this?

**Comment by nhynes** [comment]
:shushing_face:

**Comment by nhynes** [comment]
this is never going to happen
